export default {
  GET_NEWS: 'GET_NEWS',
  INCREMENT_PAGE: 'INCREMENT_PAGE',
  SORT_BY_TIME: 'SORT_BY_TIME',
  SORT_BY_TITLE: 'SORT_BY_TITLE',
  SORT_BY_DOMAIN: 'SORT_BY_DOMAIN',
  SET_LAST_ITEM_ID: 'SET_LAST_ITEM_ID'
};